/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studio;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.BigDecimal;
public class AddClientDialog extends javax.swing.JDialog {
    
    private ClientDAo  clientDAO;
    private Clients clients;
    
    private Client1 previousClient=null;
    private boolean updateMode=false;
        
    public AddClientDialog(ClientDAo theClientdao,Clients theClients,Client1 thePreviousClient,boolean theUpdateMode){
        this();
        clientDAO = theClientdao;
        clients = theClients;
        previousClient = thePreviousClient;
        updateMode = theUpdateMode;
        
        if (updateMode){
            setTitle("Update Clients");
            
            populateGui(previousClient);
        }
    }
    private void populateGui(Client1 theClient){
        
    }

    /**
     * Creates new form AddClientDialog
     */
    public AddClientDialog(Clients theClient,ClientDAo theClientDAO,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         clientDAO=theClientDAO;
        clients=theClient;
    }

    AddClientDialog(Clients aThis, ClientDAo clientdao) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        NameLabel1 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NatureComboBox = new javax.swing.JComboBox();
        Payable = new javax.swing.JLabel();
        YesRadioButton1 = new javax.swing.JRadioButton();
        NoRadioButton2 = new javax.swing.JRadioButton();
        ProjectProgressLabel = new javax.swing.JLabel();
        StaffAssignedLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        AmountTextField = new javax.swing.JTextField();
        staffAssignedTextField = new javax.swing.JTextField();
        EquipmentLebal = new javax.swing.JLabel();
        EquipmentComboBox = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ProgressComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Client");

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Add New Cleint");
        jInternalFrame1.setVisible(true);

        NameLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nature:");

        NatureComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NatureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recording", "Renting" }));
        NatureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NatureComboBoxActionPerformed(evt);
            }
        });

        Payable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Payable.setText("Payable:");

        YesRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        YesRadioButton1.setText("Yes");

        NoRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NoRadioButton2.setText("No");

        ProjectProgressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ProjectProgressLabel.setText("Progress:");

        StaffAssignedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StaffAssignedLabel.setText("Staff Assigned:");

        AmountLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AmountLabel.setText("Amount:");

        EquipmentLebal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EquipmentLebal.setText("Equipment:");

        EquipmentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mic", "Keyboard", "Mixer", "Sound System" }));

        SaveButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.setToolTipText("");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ProgressComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Complete", "Incomplete" }));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(ProjectProgressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ProgressComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(StaffAssignedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffAssignedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AmountLabel)
                                    .addComponent(Payable))
                                .addGap(13, 13, 13)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(YesRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(NoRadioButton2))
                                    .addComponent(AmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(EquipmentLebal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EquipmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Payable)
                    .addComponent(YesRadioButton1)
                    .addComponent(NoRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AmountLabel)
                    .addComponent(AmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectProgressLabel)
                    .addComponent(ProgressComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffAssignedLabel)
                    .addComponent(staffAssignedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipmentLebal)
                    .addComponent(EquipmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        NameLabel1.getAccessibleContext().setAccessibleName("CientName");
        Payable.getAccessibleContext().setAccessibleName("PayableLabel");
        staffAssignedTextField.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NatureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NatureComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NatureComboBoxActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        saveClient();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed
    protected void saveClient(){
        //get client info from gui
        String ClientName = NameTextField.getText();
        ComboBoxModel ClientNature = NatureComboBox.getModel();
        String AmountStr = AmountTextField.getText();
        BigDecimal Amount = convertStringToBigDecimal(AmountStr);
        ComboBoxModel ProjectProgress = ProgressComboBox1.getModel() ;
        String StaffAssigned = staffAssignedTextField.getText();
        ComboBoxModel Equipment = EquipmentComboBox.getModel();
        
        Client1 tempClient = null;
        if(updateMode){
            tempClient = previousClient;
            
            tempClient.setClientName(ClientName);
            tempClient.setClientNature(ClientNature);
            tempClient.setAmount(Amount);
            tempClient.setProjectProgress(ProjectProgress);
            tempClient.setStaffAssigned(StaffAssigned);
            tempClient.setEquipment(Equipment);
        }
        else{
            tempClient = new Client1(ClientName, ClientNature, Amount, ProjectProgress, StaffAssigned, Equipment);
        }
        try{
            //save Client
            if(updateMode){
                clientDAO.updateClient(tempClient);
            }
            else{
                clientDAO.addClient(tempClient);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(clients,"Error Message Client:" +ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
                Clients tempClients= new Clients(ClientName, ClientNature, Amount,ProjectProgress, StaffAssigned, Equipment);
        try{

        //save to database
        clientDAO.addClient(tempClients);
        //close dialog
        setVisible(false);
        dispose();
        //refresh gui list
        clients.refreshClientsView();
        //show success message
        JOptionPane.showMessageDialog(clients, "Clent added Successfully","Client Added",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception ex){
    JOptionPane.showMessageDialog(clients, "Error saving client:"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddClientDialog dialog = new AddClientDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox EquipmentComboBox;
    private javax.swing.JLabel EquipmentLebal;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JComboBox NatureComboBox;
    private javax.swing.JRadioButton NoRadioButton2;
    private javax.swing.JLabel Payable;
    private javax.swing.JComboBox ProgressComboBox1;
    private javax.swing.JLabel ProjectProgressLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel StaffAssignedLabel;
    private javax.swing.JRadioButton YesRadioButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField staffAssignedTextField;
    // End of variables declaration//GEN-END:variables

    private BigDecimal convertStringToBigDecimal(String AmountStr) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
